In [4]:
import pandas as pd

In [2]:
!pip install geopandas

Collecting geopandas
  Downloading https://files.pythonhosted.org/packages/f7/a4/e66aafbefcbb717813bf3a355c8c4fc3ed04ea1dd7feb2920f2f4f868921/geopandas-0.8.1-py2.py3-none-any.whl (962kB)
     |████████████████████████████████| 972kB 2.8MB/s
Requirement already satisfied: shapely in /usr/local/lib/python3.6/dist-packages (from geopandas) (1.7.1)
Requirement already satisfied: pandas>=0.23.0 in /usr/local/lib/python3.6/dist-packages (from geopandas) (1.0.5)
Collecting pyproj>=2.2.0
  Downloading https://files.pythonhosted.org/packages/e5/c3/071e080230ac4b6c64f1a2e2f9161c9737a2bc7b683d2c90b024825000c0/pyproj-2.6.1.post1-cp36-cp36m-manylinux2010_x86_64.whl (10.9MB)
     |████████████████████████████████| 10.9MB 17.6MB/s
Collecting fiona
  Downloading https://files.pythonhosted.org/packages/ec/20/4e63bc5c6e62df889297b382c3ccd4a7a488b00946aaaf81a118158c6f09/Fiona-1.8.13.post1-cp36-cp36m-manylinux1_x86_64.whl (14.7MB)
     |████████████████████████████████| 14.7MB 235kB/s
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (2.8.1)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (1.18.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (2018.9)
Collecting cligj>=0.5
  Downloading https://files.pythonhosted.org/packages/e4/be/30a58b4b0733850280d01f8bd132591b4668ed5c7046761098d665ac2174/cligj-0.5.0-py3-none-any.whl
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (1.15.0)
Requirement already satisfied: click<8,>=4.0 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (7.1.2)
Collecting click-plugins>=1.0
  Downloading https://files.pythonhosted.org/packages/e9/da/824b92d9942f4e472702488857914bdd50f73021efea15b4cad9aca8ecef/click_plugins-1.1.1-py2.py3-none-any.whl
Collecting munch
  Downloading https://files.pythonhosted.org/packages/cc/ab/85d8da5c9a45e072301beb37ad7f833cd344e04c817d97e0cc75681d248f/munch-2.5.0-py2.py3-none-any.whl
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (20.1.0)
Installing collected packages: pyproj, cligj, click-plugins, munch, fiona, geopandas
Successfully installed click-plugins-1.1.1 cligj-0.5.0 fiona-1.8.13.post1 geopandas-0.8.1 munch-2.5.0 pyproj-2.6.1.post1

In [3]:
import geopandas as gpd

In [ ]:
!apt-get install libgeos++ libproj-dev
!pip install geoviews

In [5]:
import geoviews as gv
import geoviews.feature as gf
from geoviews import opts
from cartopy import crs 
import geoviews.tile_sources as gts
gv.extension('bokeh', 'matplotlib')

Output hidden; open in https://colab.research.google.com to view.

In [6]:
stockholm = ( 18.070625,59.320462, 'Stockholm')
london = ( -0.135593, 51.507020, 'London')
istanbul = ( 28.981856, 41.008327, 'Istanbul')
mogadishu = ( 45.299626, 2.042388, 'Mogadishu')

In [7]:
cities = gv.Points([stockholm, london, istanbul, mogadishu], vdims='City')
cities.dframe()

           x          y       City
0  18.070625  59.320462  Stockholm
1  -0.135593  51.507020     London
2  28.981856  41.008327   Istanbul
3  45.299626   2.042388  Mogadishu

In [19]:
cities.opts(opts.Points(global_extent=True, width=500, height=475, size=12, color='black'))

:Points   [x,y]   (City)

In [21]:
gv.Layout([ts.relabel(name) for name, ts in gts.tile_sources.items()]).opts('WMTS', xaxis=None, yaxis=None, width=225, height=225).cols(6)

:Layout
   .WMTS.CartoDark             :WMTS   [Longitude,Latitude]
   .WMTS.CartoEco              :WMTS   [Longitude,Latitude]
   .WMTS.CartoLight            :WMTS   [Longitude,Latitude]
   .WMTS.CartoMidnight         :WMTS   [Longitude,Latitude]
   .WMTS.StamenTerrain         :WMTS   [Longitude,Latitude]
   .WMTS.StamenTerrainRetina   :WMTS   [Longitude,Latitude]
   .WMTS.StamenWatercolor      :WMTS   [Longitude,Latitude]
   .WMTS.StamenToner           :WMTS   [Longitude,Latitude]
   .WMTS.StamenTonerBackground :WMTS   [Longitude,Latitude]
   .WMTS.StamenLabels          :WMTS   [Longitude,Latitude]
   .WMTS.EsriImagery           :WMTS   [Longitude,Latitude]
   .WMTS.EsriNatGeo            :WMTS   [Longitude,Latitude]
   .WMTS.EsriUSATopo           :WMTS   [Longitude,Latitude]
   .WMTS.EsriTerrain           :WMTS   [Longitude,Latitude]
   .WMTS.EsriReference         :WMTS   [Longitude,Latitude]
   .WMTS.EsriOceanBase         :WMTS   [Longitude,Latitude]
   .WMTS.EsriOceanReference    :WMTS   [Longitude,Latitude]
   .WMTS.OSM                   :WMTS   [Longitude,Latitude]
   .WMTS.Wikipedia             :WMTS   [Longitude,Latitude]

In [22]:
gv.tile_sources.OSM.opts( width=800, height=600)

:WMTS   [Longitude,Latitude]

In [24]:
(gv.tile_sources.CartoDark * cities).opts(opts.Points(global_extent=True, width=800, height=600, size=8, color='red'))

:Overlay
   .WMTS.I   :WMTS   [Longitude,Latitude]
   .Points.I :Points   [x,y]   (City)

In [ ]:
projections = [crs.RotatedPole, crs.LambertCylindrical, crs.Geostationary, 
 crs.AzimuthalEquidistant, crs.OSGB, crs.EuroPP, crs.Gnomonic,
 crs.Mollweide, crs.OSNI, crs.Miller, crs.InterruptedGoodeHomolosine,
 crs.SouthPolarStereo, crs.Orthographic, crs.NorthPolarStereo, crs.Robinson,
 crs.LambertConformal, crs.AlbersEqualArea]
proj_layout = gv.Layout([gf.coastline.relabel(group=p.__name__).opts(projection=p(), backend='matplotlib')
 for p in projections])
gv.output(proj_layout, backend='matplotlib')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: The default value for the *approx* keyword argument to OSGB will change from True to False after 0.18.
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: The default value for the *approx* keyword argument to OSNI will change from True to False after 0.18.
  import sys
/usr/local/lib/python3.6/dist-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)

In [8]:
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world.head()

     pop_est  ...                                           geometry
0     920938  ...  MULTIPOLYGON (((180.00000 -16.06713, 180.00000...
1   53950935  ...  POLYGON ((33.90371 -0.95000, 34.07262 -1.05982...
2     603253  ...  POLYGON ((-8.66559 27.65643, -8.66512 27.58948...
3   35623680  ...  MULTIPOLYGON (((-122.84000 49.00000, -122.9742...
4  326625791  ...  MULTIPOLYGON (((-122.84000 49.00000, -120.0000...

[5 rows x 6 columns]

In [10]:
world_poly = gv.Polygons(world).opts(color='gray', line_color='white' )

In [11]:
cities_points = gv.Points(cities).opts(opts.Points(global_extent=True, width=800, height=600, size=8, color='red', tools=['hover']))

In [ ]:
(world_poly * gf.ocean * cities_points).opts(projection=crs.Orthographic(central_longitude=0.1, central_latitude=22), global_extent=True, width=600, tools=['hover'])

/usr/local/lib/python3.6/dist-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: https://naciscdn.org/naturalearth/110m/physical/ne_110m_ocean.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)

In [ ]:
gv.Polygons(world, vdims=[‘name’, 'pop_est', 'gdp_md_est'], label='World Population').opts(color='pop_est',cmap='blues', colorbar=True, xaxis=None, yaxis=None,toolbar=’above’, width=1000, height=700, tools=['hover''])

In [ ]:
coountries_grouped = gv.Polygons(world, vdims=['name', 'continent'],label='Continent').groupby('continent')

In [ ]:
continents = coountries_grouped.opts(width=600, height=400, tools=['hover'], infer_projection=True)
continents